GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/620bfeebf4c1e07a9f4a6750

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "1337768967"
}